name: Deploy Lambdas

on:
  push:
    branches:
      - main  # Adjust based on your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS CLI (for zip packaging)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          pip install awscli

      - name: Load Environment Variables
        run: |
          # Load environment variables from a file into a format usable for Lambda
          export $(grep -v '^#' environmentvariables.txt | xargs)

      - name: Deploy Lambdas
        run: |
          #!/bin/bash

          # Define your base path for Lambda folders and AWS details
          BASE_PATH="./"          # Adjust based on your base path for Lambda folders
          AWS_REGION="ap-south-1" # Your AWS region
          ROLE_ARN="arn:aws:iam::***:role/Lambdarole" # Your actual role ARN

          # Loop through each top-level directory
          for dir in "$BASE_PATH"*/; do
              if [ -f "$dir/index.js" ]; then  # Check if index.js exists in the folder
                  FUNCTION_NAME=$(basename "$dir")  # Get the name of the directory as function name

                  # Create a zip file containing the index.js file
                  echo "Creating zip file for $FUNCTION_NAME..."
                  cd "$dir" || { echo "Failed to change directory to $dir"; exit 1; }

                  zip -r "../$FUNCTION_NAME.zip" .   # Zip all contents of the folder (including index.js)
                  echo "Contents of the zip file:"
                  unzip -l "../$FUNCTION_NAME.zip"    # List the contents of the created zip file

                  cd .. || { echo "Failed to change back to base directory"; exit 1; }

                  # Check if the Lambda function already exists
                  if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
                      echo "Updating existing Lambda function $FUNCTION_NAME..."

                      # Update the existing Lambda function code
                      aws lambda update-function-code --function-name "$FUNCTION_NAME" \
                          --zip-file fileb://"$FUNCTION_NAME.zip" --region "$AWS_REGION"

                      # Wait for a few seconds to ensure the code update completes
                      echo "Waiting for the Lambda update to complete..."
                      sleep 30

                      # Update the Lambda function configuration (memory, timeout, ephemeral storage, and environment variables)
                      aws lambda update-function-configuration --function-name "$FUNCTION_NAME" \
                          --memory-size 1024 \
                          --timeout 840 \
                          --ephemeral-storage '{"Size": 512}' \
                          --environment "Variables={DB_HOST=$DB_HOST,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,API_KEY=$API_KEY}" \
                          --region "$AWS_REGION"
                  else
                      echo "Creating new Lambda function $FUNCTION_NAME..."

                      # Create a new Lambda function with specified configuration and environment variables
                      aws lambda create-function --function-name "$FUNCTION_NAME" \
                          --runtime nodejs18.x \
                          --handler index.handler \
                          --role "$ROLE_ARN" \
                          --memory-size 1024 \
                          --timeout 840 \
                          --ephemeral-storage '{"Size": 512}' \
                          --zip-file fileb://"$FUNCTION_NAME.zip" \
                          --region "$AWS_REGION" \
                          --environment "Variables={DB_HOST=$DB_HOST,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,API_KEY=$API_KEY}"
                  fi

                  # Clean up the zip file after upload
                  rm "$FUNCTION_NAME.zip"
              else
                  echo "No index.js found in $dir, skipping..."
              fi
          done

