name: Deploy Lambdas

on:
  push:
    branches:
      - main  # Adjust based on your main branch
    paths:
      - '**/'  # Trigger on any folder changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Hardcoded region

      - name: Deploy Lambda Functions
        run: |
          BASE_PATH="./"  # Adjust based on your base path for Lambda folders
          AWS_REGION="ap-south-1"  # Hardcoded region
          ROLE_ARN="arn:aws:iam::905418239558:role/Lambdarole"  # Replace with your actual IAM role ARN

          # Loop through each folder in the base path
          for dir in "$BASE_PATH"/*/; do
            FUNCTION_NAME=$(basename "$dir")  # Get the folder name as the function name
            # Create a zip file for the Lambda function
            zip -r "$dir/$FUNCTION_NAME.zip" "$dir"
            
            # Check if the index.js file exists
            if [ -f "$dir/index.js" ]; then
              # Check if the Lambda function already exists
              if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
                echo "Updating existing Lambda function $FUNCTION_NAME..."
                
                # Update the function code
                aws lambda update-function-code --function-name "$FUNCTION_NAME" \
                  --zip-file fileb://"$dir/$FUNCTION_NAME.zip" --region "$AWS_REGION"
              else
                echo "Creating new Lambda function $FUNCTION_NAME..."
                
                # Create the new Lambda function with the same role for all
                aws lambda create-function --function-name "$FUNCTION_NAME" \
                  --runtime nodejs18.x \
                  --handler index.handler \
                  --role "$ROLE_ARN" \
                  --region "$AWS_REGION" \
                  --zip-file fileb://"$dir/$FUNCTION_NAME.zip"
              fi
            else
              echo "index.js not found in $dir. Skipping function creation for $FUNCTION_NAME."
            fi
          done

